; Dispositivo residencia (ESP32-CAM) — scan BLE + cámara + WiFi
; P1: compila esqueleto. P3: NimBLE scan + RSSI. P4: cámara. P6: upload WiFi.
[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv   ; espacio para cámara + BLE + WiFi
build_flags =
    -DBOARD_HAS_PSRAM
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.1
