; Collar ESP32-C3 Mini / SuperMini — beacon BLE de PeTrack
; La SuperMini usa el mismo SoC que la ESP32-C3-DevKitM-1.
[env:esp32c3mini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_protocol = esptool
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.1
